[package]
name = "rustafarian"
version = "0.1.0"
authors = ["Vladislav Mamon <vlad@nrsk.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
opt-level = "s"
panic = "abort"
debug = false
